### ISSUE TITLE
's-Gravenhage vs s-Gravenhage

### ISSUE THREAD

**Issue by dstotijn** [Kapulara/COVID-19-NL#2]
It seems that RIVM dropped the leading apostrophe for 's-Gravenhage on 3/27/2020. 
Do you think this needs to be corrected for the files prior of 3/27/2020? It's not a major issue since the municipality number is still the same.

FYI, ran into this here: https://grafana.v0x.nl/d/J8O2R8rZk/covid-19-nl?orgId=1&var-municipality=%27s-Gravenhage&var-municipality=s-Gravenhage

![image](https://user-images.githubusercontent.com/983924/77962529-0d50eb80-72dc-11ea-9b6b-87eb1fc98db3.png)

**Comment by Kapulara** [comment]
Have changed this all references with '-s to -s, also made sure it doesn't go through the parser. Thanks for this! 😄 👍
